[package]
name = "test-autocxx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autocxx = "0.27.0"
cxx = "1.0"

[build-dependencies]
autocxx-build = "0.27.0"
autocxx-engine = "0.27.0"
